Farabi/bot-1856/fix tutorial tab and tours
deriv-com/bot pull request #29
Opened 2024-07-23 07:11 UTC by farabi-deriv

## Changes:

- Fixed guide tab contents such as deriv bot videos in tutorials tab
- Fixed FAQ accordion content in tutorials tab 
- Fixed quick strategy guides and details content in tutorials tab 
- Fixed searching in tutorials tab
- Added icons and images related to tutorials tab

2024-07-24 07:28 UTC, sandeep-deriv requested changes
Replace the IcCloseCircle with IcDbotClose or vice versa @farabi-deriv

2024-07-24 08:14 UTC, sandeep-deriv approved these changes

2024-07-25 03:42 UTC, rupato-deriv approved these changes

2024-07-25 11:19 UTC, shafin-deriv approved these changes

2024-07-25 11:30 UTC, merged